import type { NextPage } from 'next'
import Head from 'next/head'
import Item from '../components/Item'

const item = {
  name: 'בטטה קלויה',
  price: 1700,
  image:
    'https://wolt-menu-images-cdn.wolt.com/menu-images/604a145982182808dab638ac/05f526aa-9075-11eb-bc32-3e007e9d0807_____.jpeg',
  link: 'https://wolt.com/he/isr/tel-aviv/restaurant/medium-rare/itemid-604a284633a9f6f385c409fb',
}

const Home: NextPage = () => {
  return (
    <div className="px-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Item {...item} />
    </div>
  )
}

export default Home
