import type { NextPage } from 'next'
import Head from 'next/head'
import Item from '../components/Item'

const item = {
  name: 'גלידת שוקו-וניל',
  price: 2900,
  image:
    'https://wolt-menu-images-cdn.wolt.com/menu-images/5e78cb13847861e9e4ea09a8/7e13a436-5344-11eb-88e1-f6d876f57519________________.jpeg',
  link: 'https://wolt-menu-images-cdn.wolt.com/menu-images/5e78cb13847861e9e4ea09a8/7e13a436-5344-11eb-88e1-f6d876f57519________________.jpeg',
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Item {...item} />
    </div>
  )
}

export default Home
