import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useMemo, useState } from 'react'
import Item, { ItemProps } from '../components/Item'

/*const item = {
  name: 'בטטה קלויה',
  price: 1700,
  image:
    'https://wolt-menu-images-cdn.wolt.com/menu-images/604a145982182808dab638ac/05f526aa-9075-11eb-bc32-3e007e9d0807_____.jpeg',
  link: 'https://wolt.com/he/isr/tel-aviv/restaurant/medium-rare/itemid-604a284633a9f6f385c409fb',
}*/

const Home: NextPage = () => {
  const [item, setItem] = useState({ name: '' })
  const router = useRouter()
  const BASE_URL = 'woltroulette-yanshoofapp-gmailcom.vercel.app'
  useMemo(() => {
    axios
      .get(`${BASE_URL}/api/item?location=32.05784169999998,34.825958000000014`)
      .then((res) => {
        setItem(res.data)
      })
  }, [BASE_URL])
  return item.name ? (
    <div className="px-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Item {...(item as ItemProps)} />
    </div>
  ) : (
    <a></a>
  )
}

export default Home
