import axios from 'axios'
import type { NextPage } from 'next'
import loadConfig from 'next/dist/server/config'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useCallback, useMemo, useState } from 'react'
import Item, { ItemProps } from '../components/Item'
import Spinner from '../components/Spinner'

/*const item = {
  name: 'בטטה קלויה',
  price: 1700,
  image:
    'https://wolt-menu-images-cdn.wolt.com/menu-images/604a145982182808dab638ac/05f526aa-9075-11eb-bc32-3e007e9d0807_____.jpeg',
  link: 'https://wolt.com/he/isr/tel-aviv/restaurant/medium-rare/itemid-604a284633a9f6f385c409fb',
}*/

const Home: NextPage = () => {
  const [item, setItem] = useState({ name: '' })
  const [loading, setLoading] = useState(false)
  const router = useRouter()
  const lottery = useCallback(() => {
    setLoading(true)
    axios
      .get(`/api/item?location=32.05784169999998,34.825958000000014`)
      .then((res) => {
        setItem(res.data)
        setLoading(false)
      })
  }, [])

  return (
    <div className="flex flex-col items-center h-screen justify-center gap-4 px-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!loading && item.name ? (
        <Item {...(item as ItemProps)} />
      ) : (
        <Spinner className="w-10 h-10 fill-primary-500" />
      )}
      <button
        className="flex w-fit items-center font-bold justify-center h-11 px-6 gap-6 text-white rounded-lg bg-primary-500"
        onClick={() => lottery()}
      >
        הגרלה
      </button>
    </div>
  )
}

export default Home
