import axios from 'axios'
import type { NextPage } from 'next'
import loadConfig from 'next/dist/server/config'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useCallback, useMemo, useState } from 'react'
import Button from '../components/forms/Button'
import LocationInput from '../components/forms/Location'
import Item, { ItemProps } from '../components/Item'
import ItemLottery from '../components/ItemLottery'
import Spinner from '../components/Spinner'

/*const item = {
  name: 'בטטה קלויה',
  price: 1700,
  image:
    'https://wolt-menu-images-cdn.wolt.com/menu-images/604a145982182808dab638ac/05f526aa-9075-11eb-bc32-3e007e9d0807_____.jpeg',
  link: 'https://wolt.com/he/isr/tel-aviv/restaurant/medium-rare/itemid-604a284633a9f6f385c409fb',
}*/

const Home: NextPage = () => {
  const [cords, setCords] = useState([0, 0])
  console.log(cords)

  return (
    <div className="flex flex-col items-center h-screen justify-center gap-4 px-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LocationInput onChange={() => setCords} />
      <ItemLottery location={['234', '23434']} />
    </div>
  )
}

export default Home
